version: '3.3'

services:
  discord-bot:
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    container_name: discord-bot
    restart: always